ALTER TABLE pv ADD COLUMN note TINYINT(1) DEFAULT NULL;
ALTER TABLE pv ADD COLUMN allow_comments BOOLEAN DEFAULT 1;

CREATE TABLE IF NOT EXISTS pv_comments (
    id CHAR(36) PRIMARY KEY,
    pv_id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    contenu TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT 1,
    FOREIGN KEY (pv_id) REFERENCES pv(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
